export interface Mobile {
  id: string
  brand: string
  model: string
  year: string
  variants: string[]
  image: string
  accessories: number
}

const MOCK_MOBILES: Record<string, Mobile[]> = {
  Samsung: [
    {
      id: 'sam-s24-ultra',
      brand: 'Samsung',
      model: 'Galaxy S24 Ultra',
      year: '2024',
      variants: ['12GB+256GB', '12GB+512GB', '12GB+1TB'],
      image: '📱',
      accessories: 150,
    },
    {
      id: 'sam-s24',
      brand: 'Samsung',
      model: 'Galaxy S24',
      year: '2024',
      variants: ['8GB+128GB', '8GB+256GB', '8GB+512GB'],
      image: '📱',
      accessories: 142,
    },
    {
      id: 'sam-s24-plus',
      brand: 'Samsung',
      model: 'Galaxy S24+',
      year: '2024',
      variants: ['12GB+256GB', '12GB+512GB'],
      image: '📱',
      accessories: 135,
    },
    {
      id: 'sam-a55',
      brand: 'Samsung',
      model: 'Galaxy A55',
      year: '2024',
      variants: ['8GB+128GB', '8GB+256GB'],
      image: '📱',
      accessories: 98,
    },
    {
      id: 'sam-z-fold6',
      brand: 'Samsung',
      model: 'Galaxy Z Fold 6',
      year: '2024',
      variants: ['12GB+256GB', '12GB+512GB', '12GB+1TB'],
      image: '📱',
      accessories: 87,
    },
    {
      id: 'sam-z-flip6',
      brand: 'Samsung',
      model: 'Galaxy Z Flip 6',
      year: '2024',
      variants: ['12GB+256GB', '12GB+512GB'],
      image: '📱',
      accessories: 76,
    },
  ],
  Apple: [
    {
      id: 'app-iphone16-promax',
      brand: 'Apple',
      model: 'iPhone 16 Pro Max',
      year: '2024',
      variants: ['256GB', '512GB', '1TB'],
      image: '📱',
      accessories: 189,
    },
    {
      id: 'app-iphone16-pro',
      brand: 'Apple',
      model: 'iPhone 16 Pro',
      year: '2024',
      variants: ['256GB', '512GB', '1TB'],
      image: '📱',
      accessories: 176,
    },
    {
      id: 'app-iphone16',
      brand: 'Apple',
      model: 'iPhone 16',
      year: '2024',
      variants: ['128GB', '256GB', '512GB'],
      image: '📱',
      accessories: 165,
    },
    {
      id: 'app-iphone16-plus',
      brand: 'Apple',
      model: 'iPhone 16 Plus',
      year: '2024',
      variants: ['128GB', '256GB', '512GB'],
      image: '📱',
      accessories: 152,
    },
    {
      id: 'app-iphone15',
      brand: 'Apple',
      model: 'iPhone 15',
      year: '2023',
      variants: ['128GB', '256GB', '512GB'],
      image: '📱',
      accessories: 142,
    },
    {
      id: 'app-iphone15-pro',
      brand: 'Apple',
      model: 'iPhone 15 Pro',
      year: '2023',
      variants: ['128GB', '256GB', '512GB', '1TB'],
      image: '📱',
      accessories: 138,
    },
  ],
  Redmi: [
    {
      id: 'red-note13-pro',
      brand: 'Redmi',
      model: 'Note 13 Pro',
      year: '2024',
      variants: ['8GB+256GB', '12GB+256GB', '12GB+512GB'],
      image: '📱',
      accessories: 124,
    },
    {
      id: 'red-note13',
      brand: 'Redmi',
      model: 'Note 13',
      year: '2024',
      variants: ['4GB+128GB', '6GB+128GB', '8GB+256GB'],
      image: '📱',
      accessories: 112,
    },
    {
      id: 'red-12',
      brand: 'Redmi',
      model: 'Redmi 12',
      year: '2024',
      variants: ['4GB+128GB', '6GB+128GB'],
      image: '📱',
      accessories: 98,
    },
    {
      id: 'red-13',
      brand: 'Redmi',
      model: 'Redmi 13',
      year: '2024',
      variants: ['4GB+128GB', '6GB+128GB', '8GB+256GB'],
      image: '📱',
      accessories: 105,
    },
  ],
  Vivo: [
    {
      id: 'viv-x100-ultra',
      brand: 'Vivo',
      model: 'X100 Ultra',
      year: '2024',
      variants: ['12GB+512GB', '16GB+512GB', '16GB+1TB'],
      image: '📱',
      accessories: 134,
    },
    {
      id: 'viv-x100',
      brand: 'Vivo',
      model: 'X100',
      year: '2024',
      variants: ['12GB+256GB', '12GB+512GB'],
      image: '📱',
      accessories: 128,
    },
    {
      id: 'viv-v40',
      brand: 'Vivo',
      model: 'V40',
      year: '2024',
      variants: ['8GB+128GB', '8GB+256GB', '12GB+256GB'],
      image: '📱',
      accessories: 115,
    },
    {
      id: 'viv-y100',
      brand: 'Vivo',
      model: 'Y100',
      year: '2024',
      variants: ['6GB+128GB', '8GB+128GB', '8GB+256GB'],
      image: '📱',
      accessories: 92,
    },
  ],
  Oppo: [
    {
      id: 'opp-find-x7',
      brand: 'Oppo',
      model: 'Find X7',
      year: '2024',
      variants: ['12GB+256GB', '12GB+512GB'],
      image: '📱',
      accessories: 118,
    },
    {
      id: 'opp-find-x6-pro',
      brand: 'Oppo',
      model: 'Find X6 Pro',
      year: '2024',
      variants: ['12GB+512GB', '16GB+512GB'],
      image: '📱',
      accessories: 112,
    },
    {
      id: 'opp-a3-pro',
      brand: 'Oppo',
      model: 'A3 Pro',
      year: '2024',
      variants: ['8GB+128GB', '8GB+256GB'],
      image: '📱',
      accessories: 88,
    },
    {
      id: 'opp-reno-12',
      brand: 'Oppo',
      model: 'Reno 12',
      year: '2024',
      variants: ['8GB+256GB', '12GB+256GB'],
      image: '📱',
      accessories: 102,
    },
  ],
  Realme: [
    {
      id: 'rea-gt7',
      brand: 'Realme',
      model: 'GT 7',
      year: '2024',
      variants: ['12GB+256GB', '12GB+512GB'],
      image: '📱',
      accessories: 106,
    },
    {
      id: 'rea-12-pro',
      brand: 'Realme',
      model: 'Realme 12 Pro',
      year: '2024',
      variants: ['8GB+256GB', '12GB+256GB'],
      image: '📱',
      accessories: 94,
    },
    {
      id: 'rea-12',
      brand: 'Realme',
      model: 'Realme 12',
      year: '2024',
      variants: ['6GB+128GB', '8GB+256GB'],
      image: '📱',
      accessories: 82,
    },
    {
      id: 'rea-c61',
      brand: 'Realme',
      model: 'C61',
      year: '2024',
      variants: ['4GB+64GB', '4GB+128GB', '6GB+128GB'],
      image: '📱',
      accessories: 68,
    },
  ],
  Poco: [
    {
      id: 'poc-f6-pro',
      brand: 'Poco',
      model: 'F6 Pro',
      year: '2024',
      variants: ['12GB+512GB', '16GB+512GB'],
      image: '📱',
      accessories: 98,
    },
    {
      id: 'poc-f6',
      brand: 'Poco',
      model: 'F6',
      year: '2024',
      variants: ['8GB+256GB', '12GB+256GB'],
      image: '📱',
      accessories: 92,
    },
    {
      id: 'poc-x6-pro',
      brand: 'Poco',
      model: 'X6 Pro',
      year: '2024',
      variants: ['8GB+256GB', '12GB+512GB'],
      image: '📱',
      accessories: 85,
    },
    {
      id: 'poc-m6',
      brand: 'Poco',
      model: 'M6',
      year: '2024',
      variants: ['4GB+128GB', '6GB+128GB'],
      image: '📱',
      accessories: 72,
    },
  ],
  Motorola: [
    {
      id: 'mot-edge-50-pro',
      brand: 'Motorola',
      model: 'Edge 50 Pro',
      year: '2024',
      variants: ['12GB+512GB'],
      image: '📱',
      accessories: 108,
    },
    {
      id: 'mot-edge-50',
      brand: 'Motorola',
      model: 'Edge 50',
      year: '2024',
      variants: ['12GB+256GB', '12GB+512GB'],
      image: '📱',
      accessories: 102,
    },
    {
      id: 'mot-g54',
      brand: 'Motorola',
      model: 'G54',
      year: '2024',
      variants: ['8GB+128GB', '8GB+256GB'],
      image: '📱',
      accessories: 79,
    },
    {
      id: 'mot-g84',
      brand: 'Motorola',
      model: 'G84',
      year: '2024',
      variants: ['8GB+128GB', '8GB+256GB'],
      image: '📱',
      accessories: 81,
    },
  ],
  Nokia: [
    {
      id: 'nok-g42',
      brand: 'Nokia',
      model: 'G42',
      year: '2024',
      variants: ['4GB+128GB', '6GB+128GB'],
      image: '📱',
      accessories: 62,
    },
    {
      id: 'nok-x100',
      brand: 'Nokia',
      model: 'X100',
      year: '2024',
      variants: ['8GB+256GB'],
      image: '📱',
      accessories: 58,
    },
    {
      id: 'nok-c32',
      brand: 'Nokia',
      model: 'C32',
      year: '2024',
      variants: ['3GB+64GB', '4GB+64GB'],
      image: '📱',
      accessories: 45,
    },
    {
      id: 'nok-5310',
      brand: 'Nokia',
      model: '5310',
      year: '2024',
      variants: ['4GB+64GB'],
      image: '📱',
      accessories: 52,
    },
  ],
}

export function getMobilesByBrand(brand: string): Mobile[] {
  return MOCK_MOBILES[brand] || []
}

export function getAllMobiles(): Mobile[] {
  return Object.values(MOCK_MOBILES).flat()
}
